# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20160701_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='pagoHora',
            field=models.CharField(max_length=50),
        ),
    ]
